[package]
name = "mtg_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
bincode = "1.3.3"
json = "0.12.4"
serde = "1.0.147"
thiserror = "1.0.37"
